name: quan_li_chi_tieu
description: "Ứng dụng Quản Lý Chi Tiêu"
publish_to: "none"
version: 0.1.0+1

environment:
  #sdk: ^3.10.7
  sdk: ^3.10.7
dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  intl: ^0.19.0
  dio: ^5.7.0
  cached_network_image: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
